// <auto-generated />
using CoinPriceAPI.Models.Database.CoinPriceApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoinPriceAPI.Migrations
{
    [DbContext(typeof(CoinPriceApiContext))]
    [Migration("20251007185941_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CoinPriceAPI.Models.Database.CoinPriceApi.CoinModel", b =>
                {
                    b.Property<int>("CoinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CoinImg")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CoinName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("MarketValue")
                        .HasColumnType("decimal(38,8)");

                    b.Property<decimal>("PercentChange")
                        .HasColumnType("decimal(38,8)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(38,8)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalCoinCount")
                        .HasColumnType("decimal(38,8)");

                    b.Property<decimal>("TotalMarketValue")
                        .HasColumnType("decimal(38,8)");

                    b.Property<decimal>("TransactionVolume")
                        .HasColumnType("decimal(38,8)");

                    b.Property<decimal>("UsableCoin")
                        .HasColumnType("decimal(38,8)");

                    b.HasKey("CoinId");

                    b.ToTable("Coins");
                });
#pragma warning restore 612, 618
        }
    }
}
